---
title: "Reporting and Incidents of Kidnapping in Mali"
author: "Anthony Crespo"
date: "3/1/2019"
always_allow_html: yes
output:
  pdf_document: default
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,message=FALSE,warning=FALSE,quiet=TRUE,progress=FALSE,fig.align='center')
```

```{r, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(leaflet)
library(sf)
library(ggthemes)
library(scales)
library(MASS)
library(sp)
library(viridis)
library(raster)
library(urltools)
library(MASS)
library(KernSmooth)
library(leaflet.extras)
library(gridExtra)

gdelt_mali <- read_csv("/home/dsp.student01/Mali/Gdelt_Mali-data.csv")

acled <- read_csv("2017-01-01-2019-02-27-Mali.csv")
acled$event_date <- dmy(acled$event_date)

kidnapping_hits <- gdelt_mali %>% 
  filter(EventCode == '181')

#Turn $MonthYear into date so I can get a time series look at kidnapping events
kidnapping_hits$MonthYear <- ymd(kidnapping_hits$MonthYear, truncated = 1)

sources <- kidnapping_hits %>% 
  mutate(source = map_chr(SOURCEURL, function(x) suffix_extract(domain(x))[[3]])) %>%
  filter(source != "NA") %>% 
  group_by(source) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total))
```


## Top Sources of GDELT Data Reporting Hostage Taking in Mali

```{r}
sourceGraph <- sources %>% 
  filter(total >= 7) %>% 
  mutate(source = factor(source) %>% fct_reorder(total)) %>% 
  ggplot()+
  geom_col(aes(x = source, y = total), fill = "dark green")+
  labs( x = "", y = "")+
  coord_flip()

sourceGraph #Sources of GDELT information
```


## What is the Reporting Trend Over Time?

```{r}
kidnapping_hits %>% 
                group_by(MonthYear) %>% 
                summarize(total = n()) %>% 
                ggplot()+
                geom_line(aes(x = MonthYear, y = total), colour = "red")+
                geom_point(aes(x = MonthYear, y = total))+
                scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month")+
                theme(axis.text.x = element_text(angle = 90, hjust=1))+
                labs(x = "", y = "Reports of Kidnappings")
```

## Who are the Top Ten Groups Responsible?

```{r}
#Removing unnecessary columns, filtering on civ violence, and creating JNIM grouping
acled_civ_violence <- acled %>% 
                        dplyr::select(-data_id, -iso, -event_id_cnty, -year, -time_precision,
                               -assoc_actor_1, -assoc_actor_2, -region, -geo_precision,
                               -timestamp, -iso3) %>% 
                        filter(event_type == "Violence against civilians") %>% 
                        mutate(actor1=str_replace_all(actor1,"Al Mourabitoune Battalion|AQIM: Al Qaeda in the Islamic Maghreb|Ansar Dine|JNIM: Group for Support of Islam and Muslims", "JNIM"))


#How many attacks is each group committing.  I filtered by groups with 10 or more attacks
civ_attack <- acled_civ_violence %>% 
                    group_by(actor1) %>% 
                    summarize(total = n()) %>%
                    filter(total >= 10) %>% 
                    arrange(desc(total)) %>% 
                    mutate(actor1 = factor(actor1) %>% fct_reorder(total)) 
                    
                    

ggplot(civ_attack)+
  geom_col(aes(x = actor1, y = total), fill = "red")+
  labs(x = "", y = "Incidents")+
  coord_flip()
```



##Where the Reporting is Coming from Vs. Where are the Incidents Taking Place

```{r}
mali_shapefile <- getData("GADM", country='MLI', level=1) %>% 
                                                 st_as_sf()

maliMap <- ggplot(mali_shapefile)+
           geom_sf(fill = "white")+
           labs(title = 'Mali')+
           theme(plot.title = element_text(hjust = 0.5)) 
    

Plot1 <- maliMap +
  stat_density2d(data = kidnapping_hits,
                 mapping = aes(x = ActionGeo_Long, y = ActionGeo_Lat,
                               fill = ..level.., alpha = ..level..),
                 geom = "polygon") + 
  scale_fill_gradient(low = "green", high = "red") +
  guides(alpha="none") +
  labs(title = "Malian Hostage\nRelated Reporting\nJan 2017 - Feb 2019", x = "", y = "") + 
  theme(legend.position="none", 
        plot.title = element_text(hjust = 0.5))+
  theme_economist()+
  guides(fill=F)


Plot2 <- maliMap +
  stat_density2d(data = acled_civ_violence,
                 mapping = aes(x = longitude, y = latitude,
                               fill = ..level.., alpha = ..level..),
                 geom = "polygon") + 
  scale_fill_gradient(low = "green", high = "red") +
  guides(alpha="none") +
  labs(title = "Violence Against Civillians \nJan 2017 - Feb 2019\n", x = "", y = "") + 
  theme(legend.position="none", 
        plot.title = element_text(hjust = 0.5))+
  theme_economist()+
  guides(fill=F)

grid.arrange(Plot1, Plot2, nrow=1)
```


##Let Us take a Look at the Density of Reporting and Where the Individual Incidents are Happening by Group

```{r}

#Top Five Groups

JNIM <- acled_civ_violence %>% 
            filter(actor1 == "JNIM")

Unidentified <- acled_civ_violence %>% 
                  filter(actor1 == "Unidentified Armed Group (Mali)")

Malian_Mil <- acled_civ_violence %>% 
                filter(actor1 == "Military Forces of Mali (2013-)")

Dozo <- acled_civ_violence %>% 
                filter(actor1 == "Dozo Militia")

Fulani <- acled_civ_violence %>% 
                filter(actor1 == "Fulani Ethnic Militia (Mali)")

ISGS <- acled_civ_violence %>% 
            filter(actor1 == "Islamic State (Greater Sahara)")


mali.flag <- makeIcon(
  
  iconUrl = "http://flags.fmcdn.net/data/flags/w580/ml.png",
  
  iconWidth = 16,
  
  iconHeight = 16
  
)

########For leaflet heat map of GDELT data

# Compute 2-D Gaussian kernel density estimate.
kde <- bkde2D(as.data.frame(kidnapping_hits[ , c("ActionGeo_Long",
                                           "ActionGeo_Lat")]),
              bandwidth=c(bandwidth.nrd(kidnapping_hits$ActionGeo_Long),
                          bandwidth.nrd(kidnapping_hits$ActionGeo_Lat)), gridsize = c(500,500))
CL <- contourLines(kde$x1 , kde$x2 , kde$fhat)
# Extract contour line levels.
LEVS <- as.factor(sapply(CL, `[[`, "level"))
NLEV <- length(levels(LEVS))
# Convert contour lines to polygons.
pgons <- lapply(1:length(CL), function(i)
  Polygons(list(Polygon(cbind(CL[[i]]$x, CL[[i]]$y))), ID=i))
spgons = SpatialPolygons(pgons)





##############Map by gdelt heat and ACLED group activity
leaflet(kidnapping_hits) %>% 

addProviderTiles("CartoDB.Positron") %>% 
  
addPolygons(data = spgons,
            color = heat.colors(NLEV, NULL)[LEVS],
            weight = 1, opacity = .1, fillOpacity = .075,
            group = "Heatmap") %>% 

addCircleMarkers(data = JNIM,
                   
                 color = "black",
                   
                radius = 2,
                   
                popup = ~paste(
                                  "Date: ", event_date, "<br/>",
                                  
                                  "Location: ", location, "<br/>",
                                  
                                  "Report: ", notes),
                   
                  group  = "JNIM") %>% 
  
addCircleMarkers(data = Unidentified,
                   
                   color = "white",
                   
                   radius = 2,
                   
                   popup = ~paste(
                     "Date: ", event_date, "<br/>",
                     
                     "Location: ", location, "<br/>",
                     
                     "Report: ", notes),
                   
                   group  = "Unidentified")%>% 
  
  addMarkers(data = Malian_Mil,
             
                    icon = mali.flag,
    

                   
                   popup = ~paste(
                     "Date: ", event_date, "<br/>",
                     
                     "Location: ", location, "<br/>",
                     
                     "Report: ", notes),
                   
                   group  = "Malians")%>% 
  
  addCircleMarkers(data = Dozo,
                   
                   color = "yellow",
                   
                   radius = 2,
                   
                   popup = ~paste(
                     "Date: ", event_date, "<br/>",
                     
                     "Location: ", location, "<br/>",
                     
                     "Report: ", notes),
                   
                   group  = "Dozo Militia")%>% 
  
  addCircleMarkers(data = Fulani,
                   
                   color = "blue",
                   
                   radius = 2,
                   
                   popup = ~paste(
                     "Date: ", event_date, "<br/>",
                     
                     "Location: ", location, "<br/>",
                     
                     "Report: ", notes),
                   
                   group  = "Fulani Militia")%>% 
  
  addCircleMarkers(data = ISGS,
                   
                   color = "red",
                   
                   radius = 2,
                   
                   popup = ~paste(
                     "Date: ", event_date, "<br/>",
                     
                     "Location: ", location, "<br/>",
                     
                     "Report: ", notes),
                   
                   group  = "Islamic State") %>% 
  
addLayersControl(overlayGroups = c("Malians","Dozo Militia", "Fulani Militia", "JNIM", "Islamic State","Unidentified"), 
                   
                  options=layersControlOptions(collapsed=FALSE))

```

